### ISSUE TITLE
hello，

### ISSUE THREAD

**Issue by zhwshok** [jmichault/ipcam-100#1]
all ingenic t21 ip camera  is applicable？和目摄像头 how to hack？No response！
![%3BHJ()3DU}CECT)9FXI{5I](https://user-images.githubusercontent.com/44687257/110878933-11242500-8317-11eb-967c-aa3438168033.jpg)

**Comment by jmichault** [comment]
My camera was reachable by telnet, port 9527 `telnet IP 9527` for 5 minutes after booting. root password : jco66688.
