### ISSUE TITLE
Firmware in .bin format

### ISSUE THREAD

**Issue by prazsmarid** [jmichault/ipcam-100#9]
Hello,
Do you have memory dump in .bin format for this kind of camera?
Original or modified, both will be good.
Thanks in advance.

**Comment by jmichault** [comment]
Hello,
I can extract the contents of MTD partitions.
But what makes you think it can help you?

**Comment by prazsmarid** [comment]
Hello,
Thank you for your response.
My question is do you have a full 8MB flash dump (original or modded both will be good) for this camera?
I successfully erased my memory over u-boot and now the flash is fully erased :).

**Comment by jmichault** [comment]
[firmware.zip](https://github.com/jmichault/ipcam-100/files/7798303/firmware.zip)
I concatenated the 6 mtd partitions into 1 file : firmware.bin.

**Comment by jmichault** [comment]
But it's for a camera with gc2053 sensor, probably not the same as yours.

**Comment by prazsmarid** [comment]
Thank you for sharing the firmware.
With your firmware the u-boot starts to start up, but it freezes because "the spi memory is unsupported".
I found another dump on the internet (I attached it), with this dump the u-boot boots normally, the "Starting kernel..." appears, the motors inside the camera starts to rotate but after that the camera is rebooting continuously.
Do you have idea about enabling the boot messages inside the kernel? Changing the bootargs from _console=ttyS1,115200n8..._ to _console=ttyS0,115200n8_ not helped.
[combined.zip](https://github.com/jmichault/ipcam-100/files/7802332/combined.zip)

**Comment by jmichault** [comment]
No idea, but if you have a card inserted in the camera, you can try to put a file loader/run.sh on it.
This file should be executed at startup, you can put some commands to avoid reboot, i.e. «sleep 9999».
Then you can perhaps telnet to the camera.
